### ISSUE TITLE
Illustration dataset can't download

### ISSUE THREAD

**Issue by vanduong0504** [giddyyupp/ganilla#19]
I can't download your Illustration dataset from your code with this problem:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "openlibraryImageDownloaderMain.py", line 48, in <module>
    main(opts)
  File "openlibraryImageDownloaderMain.py", line 17, in main
    olh = s.OpenLibHelper(opts.openlib_username, opts.openlib_password)
  File "/content/ganilla/datasets/ganilla/datasets/scraper_openlibrary.py", line 31, in __init__
    self.browser = webdriver.Firefox(firefox_profile=profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
```

**Comment by gsoykan** [comment]
You can refer to this [stackoverflow answer](https://stackoverflow.com/a/40931903/8265079) which happened to work for me.
