### ISSUE TITLE
Illustration dataset could not be downloaded /  Crawler raises an exception

### ISSUE THREAD

**Issue by gsoykan** [giddyyupp/ganilla#20]
I have tried to download the illustration dataset according to instruction and make the crawler work.
However, it appears that it does not download any file at all. Maybe because of some change in openlibrary.org.
Also, the script does not seem to run till the end and it raises below exception. I am also attaching the correspondent browser state. 
`Traceback (most recent call last):
  File "openlibraryImageDownloaderMain.py", line 48, in <module>
    main(opts)
  File "openlibraryImageDownloaderMain.py", line 26, in main
    olh.search_author(illustrator, dir_name, lower_case_list)
  File "~/ganilla/datasets/scraper_openlibrary.py", line 52, in search_author
    search_res = self.browser.find_element_by_id("searchResults")
  File "~/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "~/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "~/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "~/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="searchResults"]
`
![image](https://user-images.githubusercontent.com/11638870/113997842-3138fc80-9861-11eb-8cb1-4febb355770a.png)

**Comment by 741736152** [comment]
Can you downloaded the Illustration datasets?

**Comment by giddyyupp** [comment]
Hello,
Yes indeed looks like the website changed the interface since you got this error: "Message: Unable to locate element: [id="searchResults"]". I am sorry but you need to debug step by step and try to locate the objects by inspecting the website. 
And if you managed to make it working again please open a PR.
Cheers!
