### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by simpsus** [giddyyupp/ganilla#5]
Thank you very much @kevroy314 for the instructions for Windows 10.
I substituted the pip calls with conda as pip does not target the newly created environment in my case.
Executing the command 
`python .\test.py --dataroot .\datasets\monet2photo\testB --name AS_pretrained --model test --checkpoints_dir .\checkpoints\ --loadSize 512 --fineSize=512`
I get the following error
`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 2.00 GiB total capacity; 94.70 MiB already allocated; 16.35 MiB free; 112.00 MiB reserved in total by PyTorch)`

Which does not seem like a ganilla issue at all. After some googling I think this is due to a memory leak, a batch size, training not wrapped in a function call or ...

So this is more like a question: Have you ever encountered this? Is there some way for me to investigate further?

**Comment by simpsus** [comment]
Output of the command from the readme.md

` python test.py --dataroot datasets/monet2photo/testB --name AS_pretrained --model test
----------------- Options ---------------
             aspect_ratio: 1.0
               batch_size: 1
          checkpoints_dir: ./checkpoints/
         cityscape_fnames: ./datasets/cityscapes_test_file_names.txt
               cityscapes: False
                 dataroot: datasets/monet2photo/testB           [default: ./datasets/photo2axel]
             dataset_mode: single
                direction: AtoB
          display_winsize: 256
                    epoch: 100
                     eval: False
                 fineSize: 256
              fpn_weights: [1.0, 1.0, 1.0, 1.0]
                  gpu_ids: 0
                init_gain: 0.02
                init_type: normal
                 input_nc: 3
                  isTrain: False                                [default: None]
                 loadSize: 256
         max_dataset_size: inf
                    model: test
             model_suffix:
               n_layers_D: 3
                     name: AS_pretrained                        [default: photo2axel_ganilla]
                      ndf: 64
                     netD: basic
                     netG: resnet_fpn
                      ngf: 64
               no_dropout: True
                  no_flip: False
                     norm: instance
                    ntest: inf
                 num_test: 751
              num_threads: 8
                output_nc: 3
                    phase: test
           resize_or_crop: resize_and_crop
              results_dir: ./results/
           serial_batches: False
                   suffix:
                  verbose: False
----------------- End -------------------
dataset [SingleImageDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints/AS_pretrained\100_net_G.pth
---------- Networks initialized -------------
[Network G] Total number of parameters : 7.228 M
-----------------------------------------------
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    model.test()
  File "C:\Users\basti\Documents\GitHub\ganilla\models\base_model.py", line 57, in test
    self.forward()
  File "C:\Users\basti\Documents\GitHub\ganilla\models\test_model.py", line 48, in forward
    self.fake_B = self.netG(self.real_A)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Documents\GitHub\ganilla\models\networks.py", line 735, in forward
    out = self.fpn([x1, x2, x3, x4]) # use all resnet layers
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Documents\GitHub\ganilla\models\networks.py", line 623, in forward
    P2_x = self.rp4(P2_upsampled_x)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\padding.py", line 163, in forward
    return F.pad(input, self.padding, 'reflect')
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\functional.py", line 2879, in pad
    return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 2.00 GiB total capacity; 92.20 MiB already allocated; 9.25 MiB free; 122.00 MiB reserved in total by PyTorch)`

**Comment by simpsus** [comment]
and one for training

`python train.py --dataroot ./datasets/monet2photo --name maps_cyclegan --model cycle_gan --netG resnet_fpn
----------------- Options ---------------
               batch_size: 1
                    beta1: 0.5
          checkpoints_dir: ./checkpoints/
           continue_train: False
                 dataroot: ./datasets/monet2photo               [default: ./datasets/photo2axel]
             dataset_mode: unaligned
                direction: AtoB
              display_env: main
             display_freq: 400
               display_id: 0
            display_ncols: 4
             display_port: 8097
           display_server: http://localhost
          display_winsize: 256
                    epoch: 100
              epoch_count: 1
                 fineSize: 256
              fpn_weights: [1.0, 1.0, 1.0, 1.0]
                  gpu_ids: 0
                init_gain: 0.02
                init_type: normal
                 input_nc: 3
                  isTrain: True                                 [default: None]
                 lambda_A: 10.0
                 lambda_B: 10.0
          lambda_identity: 0.5
                 loadSize: 286
                       lr: 0.0002
           lr_decay_iters: 50
                lr_policy: lambda
         max_dataset_size: inf
                    model: cycle_gan
               n_layers_D: 3
                     name: maps_cyclegan                        [default: photo2axel_ganilla]
                      ndf: 64
                     netD: basic
                     netG: resnet_fpn
                      ngf: 64
                    niter: 100
              niter_decay: 100
               no_dropout: True
                  no_flip: False
                  no_html: False
                 no_lsgan: False
                     norm: instance
              num_threads: 8
                output_nc: 3
                    phase: train
                pool_size: 50
               print_freq: 100
           resize_or_crop: resize_and_crop
          save_epoch_freq: 5
         save_latest_freq: 5000
           serial_batches: False
                   suffix:
         update_html_freq: 1000
                  verbose: False
----------------- End -------------------
dataset [UnalignedDataset] was created
#training images = 6287
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
model [CycleGANModel] was created
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 7.228 M
[Network G_B] Total number of parameters : 7.228 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M
-----------------------------------------------
create web directory ./checkpoints/maps_cyclegan\web...
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters()
  File "C:\Users\basti\Documents\GitHub\ganilla\models\cycle_gan_model.py", line 140, in optimize_parameters
    self.forward()
  File "C:\Users\basti\Documents\GitHub\ganilla\models\cycle_gan_model.py", line 83, in forward
    self.fake_B = self.netG_A(self.real_A)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Documents\GitHub\ganilla\models\networks.py", line 730, in forward
    x1 = self.layer1(x)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Documents\GitHub\ganilla\models\networks.py", line 498, in forward
    out = F.relu(self.bn1(self.conv1(self.rp1(x))))
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\modules\padding.py", line 163, in forward
    return F.pad(input, self.padding, 'reflect')
  File "C:\Users\basti\Anaconda3\envs\ganilla\lib\site-packages\torch\nn\functional.py", line 2879, in pad
    return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 140.53 MiB already allocated; 17.60 MiB free; 148.00 MiB reserved in total by PyTorch)`

**Comment by giddyyupp** [comment]
hello, 2 GB of GPU memory is the problem here. I guess at least 4 or 6GB of GPU memory is required to run this code.

**Comment by simpsus** [comment]
thank you  very much for your answer. Is there any way I can adjust parameters/settings to make it work with 2GB?

**Comment by giddyyupp** [comment]
hmm currently I can't think of a solution. batch size is already 1, and it is not feasible to change Generator part. how about running it on a Colab notebook?

**Comment by simpsus** [comment]
Thanks again for your help. I will check this out. I saw it in another issue.
